### ISSUE TITLE
Execution queue freezes for MA controller

### ISSUE THREAD

**Issue by mrmueller** [lithnet/miis-autosync#157] opened 2018-12-10 13:25 UTC
Hi,

First of all, thanks a lot for this great tool. It imporved our processing times a lot.
Lately it is a bit unreliable tough.

I use a Scheduled Interval trigger and after some time it just stops working. I am unsure how to provide more accurate information than by printscreens. See below.

![autosync2](https://user-images.githubusercontent.com/9515311/49735315-384aa280-fc87-11e8-944c-c32df5314d24.png)
![autosync1](https://user-images.githubusercontent.com/9515311/49735316-384aa280-fc87-11e8-8d30-6336a2fb5ed3.png)
![autosync3](https://user-images.githubusercontent.com/9515311/49735547-c4f56080-fc87-11e8-9ab5-0039923045de.png)

Thanks for your help and let me know if and how i should provide more  information.

**Comment by mrmueller** [comment] 2018-12-11 17:09
@ryannewington sorry for the late answer. I dont have that folder. Will have to look into it tomorrow

**Comment by jakolars** [comment] 2018-12-12 13:07
I also have been seing this. It seems the trigger runs one time, but is not triggered for the next run. Here are the log entries from the one time the trigger runs.
```2018-12-10 18:44:59.5984|TRACE|PIFU IST MA: Got queue request for Full Sync with id 13399
2018-12-10 18:44:59.5984| INFO|PIFU IST MA: Added Full Sync to the execution queue (triggered by: Scheduled interval: Full Sync every 1.00:00:00 starting from tirsdag 28. august 2018 18.45.00)
2018-12-10 18:44:59.5984| INFO|PIFU IST MA: Current queue: Full Sync*
2018-12-10 18:44:59.5984|TRACE|PIFU IST MA: LOCK: WAIT: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:44:59.5984|TRACE|PIFU IST MA: LOCK: CLEARED: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:44:59.5984| INFO|PIFU IST MA: Entering exclusive mode for Full Sync
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: SYNCOBJECT: WAIT: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: SYNCOBJECT: LOCKED: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: WAIT: GlobalExclusiveOperationLock: WaitAndTakeLockWithSemaphore
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: CLEARED: GlobalExclusiveOperationLock: WaitAndTakeLockWithSemaphore
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: TAKE: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: SYNCOBJECT: UNLOCKED: GlobalExclusiveOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273| INFO|PIFU IST MA: Waiting for all MAs to complete
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: WAIT: AllMaLocalOperationLocks: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: CLEARED: AllMaLocalOperationLocks: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273| INFO|PIFU IST MA: Waiting to take sync lock
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: WAIT: GlobalSynchronizationStepLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6273|TRACE|PIFU IST MA: LOCK: TAKE: GlobalSynchronizationStepLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6429|TRACE|PIFU IST MA: LOCK: WAIT: localOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6429|TRACE|PIFU IST MA: LOCK: TAKE: localOperationLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6429|TRACE|PIFU IST MA: LOCK: WAIT: GlobalStaggeredExecutionLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6429|TRACE|PIFU IST MA: LOCK: TAKE: GlobalStaggeredExecutionLock: TakeLocksAndExecuteOld
2018-12-10 18:45:01.6429|TRACE|PIFU IST MA: SLEEP: ExecutionStaggerInterval: 00:00:01: TakeLocksAndExecuteOld
2018-12-10 18:45:02.6514|TRACE|PIFU IST MA: LOCK: RELEASE: GlobalStaggeredExecutionLock: TakeLocksAndExecuteOld
2018-12-10 18:45:02.6514| INFO|PIFU IST MA: Locks obtained in 00:00:03
2018-12-10 18:45:02.6514| INFO|PIFU IST MA: Executing Full Sync```

**Comment by ryannewington** [comment] 2018-12-13 05:03
@mrmueller Does the whole engine stop, or just the single MA gets stuck? Are there any patterns to the problem, (eg same MA, or always get stuck on the same job) or is it random?

**Comment by ryannewington** [comment] 2018-12-13 05:05
@jakolars are you seeing the same issue (controller freezes and stops processing altogether), or a problem with scheduled runs not happening when you expect them to?

**Comment by jakolars** [comment] 2018-12-13 07:20
@ryannewington the controller does not freeze. That schedueled runs seems to stop happening after their first run. If my problem is unrelated, should i open a seperate issue?

**Comment by mrmueller** [comment] 2018-12-13 12:19
@ryannewington only the affected MA stops. All other MAs continue to work.
I am seeing a pattern that two MA's run into problems. MA_HR & MA_Identity. However, I am not sure if it is the same problem all the time. I will look more closely next time it happens.

I managed to remove the missing management agent. Thanks

**Comment by ryannewington** [comment] 2018-12-13 21:19
@jakolars yes it sounds like a different issue, lets work on yours in a new issue. Can you open a new issue, and email me the logs covering the event. Please let me know in the email the name of the MA, the trigger in question, the time that the scheduled task ran, and when you expected it to run, but it did not.

**Comment by mrmueller** [comment] 2018-12-14 08:14
@ryannewington more in the range of once a month. I would install a debug build in my dev environment first. maybe we are lucky enough to capture the issue there. 

Today I seem to have a similar problem to what @jakolars describes. It does no loger execute the triggers for some MA's but this time there is no reason provided (nothing is queued on the affected MA). 

I will capture the logs and some screenshots and open another issue.

**Comment by ryannewington** [comment] 2018-12-18 23:23
@mrmueller When it happens again, are you able to take a memory dump of the autosync process. Using Task Manager, just right-click on `Lithnet.Miiserver.Autosync.exe` and choose 'create dump file'. If you can zip that and send me a link to download it, i'll get a better idea of what is going on. There is nothing immediately obvious in the logs, and I've been unable to reproduce it in my own environment so far.

**Comment by mrmueller** [comment] 2018-12-19 11:46
Will do. So far I have not seen this issue again.

**Comment by mrmueller** [comment] 2019-02-06 13:43
@ryannewington This has still not happened again. May this be related to #158 and thus fixed now? We can close this issue if you want, i can reopen should it happen again.

**Comment by ryannewington** [comment] 2019-02-07 05:15
@mrmueller how strange. It is possible another code modification inadvertently fixed this issue. The locking mechanisms are quite complex and there have been changes in the build you are using now. But yes, let's close the issue for now. If you do see it, reopen this case and send me the memory dump we discussed and we can continue troubleshooting.

**Comment by mrmueller** [comment] 2019-02-13 08:46
@ryannewington  I was out of the office for few days and the issue seems to have happened again. How strange is that. I sent you a link where you can download the logfiles, memory dump and a few screenshots.

Affected MA: MA_HR, MA_Identity
Time: for MA_HR, problems started 12.02.2016 06:05. MA_Identity ran into this problem sooner, I can't see the time it first happened in the Execution Monitory because it was too long ago.

Let me know if I can provide more information.

**Comment by ryannewington** [comment] 2019-02-22 23:15
Hi @mrmueller,

Ok. I've gotten to the bottom of it. The root cause is an issue with the way 'move to the front of the execution queue is implemented'. Your triggers are using this, and a race condition exists where the item in moved in the queue and the queue falls out of sync. I've had to implement some fairly substantial changes to the entire queueing mechanism to try and fix this issue. I will take to take this version through a full round of testing before I'd be happy for it to be used in production.

As a workaround, on the trigger configuration screen, if you untick the "Add run profile to the front of the queue" you should not see this issue anymore.

You're more than welcome to test the new version yourself if you like. I'll post a link to that shortly

**Comment by ryannewington** [comment] 2019-02-22 23:18
@Manjunath-hk1 can we get this version through dev and qa for testing

[autosync.zip](https://github.com/lithnet/miis-autosync/files/2896176/autosync.zip)

**Comment by Manjunath-hk1** [comment] 2019-02-22 23:56
Sure Ryan.

Thanks,
Manju

**Comment by ryannewington** [comment] 2019-02-25 02:31
@Manjunath-hk1 fixed the issue you encountered in testing
[autosync.zip](https://github.com/lithnet/miis-autosync/files/2898777/autosync.zip)

**Comment by ryannewington** [comment] 2019-03-03 22:45
@mrmueller The version above has been stable in our environment for a week, and I'm happy for you to test that.

**Comment by ryannewington** [comment] 2019-03-06 00:05
Fixed in https://github.com/lithnet/miis-autosync/releases/tag/v1.2.6995

**Closed by ryannewington** 2019-03-06 00:05 UTC
Labels: bug

**Comment by mrmueller** [comment] 2019-03-06 12:08
@ryannewington Great thanks! Sorry i did not see the previous messages in time.
